dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - unzip
      - libx11-dev
      - libfreetype6
      - libfreetype6-dev
script:
  # Link gcc-7 and g++-7 to their standard commands
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  # Get newest cmake
  - sudo apt-get purge cmake
  - mkdir temp
  - cd temp
  - wget https://cmake.org/files/v3.10/cmake-3.10.1.tar.gz
  - tar -xzf cmake-3.10.1.tar.gz
  - cd cmake-3.10.1/
  - ./bootstrap
  - make
  - sudo make install
  - cd ..
  - cd ..
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir libs
  - mkdir libs/nana
  - mkdir libs/json
  - mkdir libs/bass
  - mkdir libs/poco
  - git clone https://github.com/cnjinhao/nana.git libs/nana
  - git clone https://github.com/nlohmann/json.git libs/json
  - git clone -b "poco-1.8.2" https://github.com/pocoproject/poco.git libs/poco
  - sudo wget http://us.un4seen.com/files/bass24-linux.zip
  - sudo unzip bass24-linux.zip -d libs/bass
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cpack -G DEB
